### PR TITLE
Resolve architectural simplification against current main (no-op)

### PR DESCRIPTION
**Pull request by metaphorics**
## Resolution

This PR is now intentionally a **no-op against current `main`**.

During conflict resolution, the proposed retirements were checked against the live branch rather than the PR's stale merge base. Current `main` still actively owns and enforces the artifacts this branch attempted to remove:

- G20 loads and checks `docs/models/*`.
- G18 CI runs `overhaul_evidence` and retains the evidence-ledger contract.
- reference-extraction CI rewrites/runs the process and reference-set harness.
- `CONSTRAINTS.md`, fixture provisioning, the reference-set contract, and the current source-compatibility/TLS policy remain live repository contracts.

Keeping the branch-side removals would therefore create a syntactically resolved but semantically broken merge. The resolution preserves current `main` for those contracts and drops the coupled cleanup (metrics/evidence API removal, G20 registration/dependency removal, formal-output ignores, and stale policy-pointer edits).

The branch now contains merge commit `160f5eec58004372c95a0ea4fb5c3e0094f5b5f9`, with the previous PR head and current `main` as parents. Its tree matches current `main`; no force-push or history rewrite was used.

## Review result

- PR diff versus current `main`: empty.
- Merge conflicts: resolved.
- GitHub mergeability: clean.
- Existing inline review threads were already resolved; the stale findings are eliminated because their changed lines no longer exist.
- CI has been triggered for the resolved head.

No code or documentation change remains to land from this PR.

### CODE REVIEW

**Review by metaphorics — COMMENTED** [review]
## Review findings and proposed follow-up PRs

Reviewed head `4a1e3dc3ae76ca69d0ef073f9d6d999a926fa722`, base `cb6698ae65284f6b38bcde34ae02c674dd14f7b3`, and CI merge tree `1745be113bd920fe638874eb11f9525f8402a5d6`. This is a source/CI review and proposal, not a clean-build or CodeRabbit approval.

### Confirmed blockers

1. **Inherited main failure: the signature checker does not compile.** The [test job](https://github.com/gosuda/bitcoin-rs/actions/runs/34371490856/job/102533557371) and [Clippy job](https://github.com/gosuda/bitcoin-rs/actions/runs/34371490856/job/102533557641) stop at 29 script-crate compilation errors. These include unavailable helpers/enum variants, `from_consensus_byte` versus the actual Result-returning `from_consensus_u8`, incorrect Taproot argument order, a missing `&Message`, unsupported VerifyFlags operations, and signatures inconsistent with evaluator callers. The checker is already broken at the base commit; these are not newly introduced by #686. Its predecessor `a0105b645440c80f72ee902a850c42bad67cfaa9` also contains the in-file checker regression tests that the current implementation removed.

2. **This PR deletes a live reference API without migrating its consumers.** `bin/bitcoin-rs/tests/overhaul_process_harness.rs` still imports and calls `bitcoin_rs_rpc::compat_manifest::reference_set`; `tests/support/process_node.rs` is another consumer identified in the existing review. The PR deletes `reference_set` and its identity types. The process harness cannot be preserved by deleting only its provider. Keep the independent reference identity and missing/substituted-binary rejection behavior while changing ownership.

3. **This PR deletes the evidence API still imported by a declared benchmark.** `crates/node/benches/sync_pipeline.rs` imports `Cell`, `CorpusIdentity`, `EvidenceIdentity`, `Interval`, `IntervalKind`, `LEDGER_SCHEMA`, `Ledger`, `Sample`, and `Sha256Hex` from node metrics. This PR removes those definitions without changing that benchmark. The benchmark target must migrate in the same change as its provider.

The run is not green: fmt, Clippy, test, and bench-smoke failed; deny and comparator-tests passed. Compilation stops also prevent downstream test/lint invocations from establishing coverage. Mergeable does not mean validated.

### Proposed PR A — fix(script): restore checker contracts and regression coverage

Base this narrowly scoped repair on current main. Recover the predecessor's evaluator-facing methods, encoding/error behavior, and regression tests, then add only the shared-cache construction required by the current interpreter. Do not mechanically restore the old file without satisfying the new cache caller, and do not rename unrelated APIs or rewrite cryptographic rules during the repair.

Acceptance: script unit tests and Core-vector tests pass with existing skip/mismatch guards unchanged; cached and uncached checking agree for signed multi-input transactions, witness and legacy paths, and Taproot annex/script-path cases; formatting and strict script/consensus linting pass. Preserve transaction/prevout association when reusing cache state.

### Proposed PR B — refactor(test-support): simplify ownership without breaking harnesses

Replace #686's provider-only deletions with a complete consumer migration. Audit production, unit-test, integration-test, and benchmark users before moving harness-only reference/evidence code to an appropriate shared test/benchmark owner. Keep only genuinely required runtime metrics behavior in production. Migrate imports, Cargo dependencies, pinned reference data, fixture provisioning, and ledger consumers together. Preserve typed fixture failures, sample histories, and the independent comparator; do not remove the tests or benchmark to make the deletion compile.

Acceptance: the process harness builds and runs with the pinned Core fixture; `sync_pipeline` builds; relevant identity/ledger rejection and round-trip tests pass; a symbol-usage audit finds no abandoned callers. Any formal-model retirement or evidence-schema change must be explicit rather than an incidental consequence of shortening files.

### Proposed PR C — chore(clippy): make every supported target warning-clean

After A/B, fix actual diagnostics across the three existing strict all-target Clippy invocations, including tests and benches. Keep behavior-changing fixes separate from mechanical lint fixes. Do not add blanket allows, relax `-D warnings`, or delete coverage. Report each feature profile's result independently; a failure in the first shell command currently prevents the later profiles from running. Preserve a failing aggregate job when any profile fails.

Acceptance: all three existing Clippy commands, rustfmt, required test profiles, and benchmark builds pass on the final integrated SHA. Backend/kernel-specific profiles must also follow the repository's existing feature-matrix policy; a default build alone is not an all-lints verdict.

### Proposed PR D — docs: consolidate guidance without changing operational contracts

Extract documentation cleanup from #686's runtime/API deletions. Make root/crate READMEs concise entry points, keep normative clauses in their existing owning contracts/policies, and link rather than repeat. Preserve generated or machine-consumed document shapes unless their generators/consumers change together. Retain historical measurements and failure evidence, distinguishing them from current results. Keep the binary's kernel-free defaults separate from the library-default promotion contract. Treat recovery and migration guidance as behavior to verify against code, not prose to shorten by assertion.

Acceptance: internal links and referenced commands/targets resolve; generated references remain reproducible; no unsupported validation-default, recovery, migration, performance, or proof claims are introduced. Existing review comments about recovery/migration/TLS policy need source verification before resolution.

### Integration order and stopping condition

Land A first. Review and integrate the existing witness-activation correction #685 rather than duplicate it; its reported validation must be re-established after integration. Then complete B/C and the independent documentation cleanup. Narrow or replace #686 with those focused changes instead of merging its current 51-file deletion sweep unchanged.

A completion claim requires current-main integration, green relevant checks on the final SHA, retained regression coverage, and fresh review of the final diff. No skipped or blocked review counts as 'no findings'.

### Execution limits

No code changes or Rust tests were executed during this review: this environment lacks Rust, and GitHub cloning/CodeRabbit installation failed on DNS resolution. The PR's CodeRabbit bot also posted a review-limit notice. No gstack, Develoop, or Matt Skills workflow was executed. The proposals above are not newly opened implementation PRs, and this review does not assert that all lints or findings are resolved.

**Comment by metaphorics** [comment]
Published the four proposed workstreams as separate implementation PRs on new branches:

- **A — #696:** verifier regression coverage binding signatures to transaction/prevout data, caller-supplied witness handling, and typed input-index errors. Main had already restored the checker, so this does not replay the obsolete repair or reintroduce the incomplete cache API.
- **B — #700:** move reference identities into test support and migrate all existing reference/process/formal consumers together. Preserve models, pins, fixture provisioning, gates, and the existing metrics/evidence API. The extraction passed 7 reference tests and compiled both consumers; its final visibility-only correction still needs final-head validation. Full all-target Clippy exposed the unchanged node metrics `chunks_exact_to_as_chunks` lint.
- **C — #695:** independent strict Clippy profiles, retaining aggregate failure and `-D warnings`. GitHub now reports this PR merged; it is not a claim that all source lints are fixed.
- **D — #698:** consolidate two documentation entry points and correct explicit REST enablement without deleting contracts, generated data, or retained evidence.

These are concrete commits, not empty proposal PRs. Each PR states its scope, acceptance criteria, and validation limits. They are focused portions of the broader cleanup, not a claim that all crates/docs or every finding are finished. Existing #685 and storage-specific PRs are not duplicated. No merge or auto-merge was performed by this publication pass.

**Comment by metaphorics** [comment]
Should resolve merge conflicts.
